services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      RESUMEFORGEDOMAIN: ${RESUMEFORGEDOMAIN}
      RESUMEFORGEPORT: ${RESUMEFORGEPORT}
    network_mode: host
    volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
